import '../../../game/domain/character_definition.dart';
import '../../../game/domain/character_id.dart';
import '../../../game/domain/run_configuration.dart';
import 'progression_models.dart';

class ProgressionCatalog {
  const ProgressionCatalog._();

  static final List<ProgressionSkill> skills = List.unmodifiable([
    _skill(
      CharacterId.jano,
      'jano_ricochet_round',
      SkillSlot.active,
      'Bala de rebote',
      5,
      1200,
      'ricochet_projectile',
      {'max_bounces': 1, 'damage_basis_points': 8000},
    ),
    _skill(
      CharacterId.jano,
      'jano_burst_protocol',
      SkillSlot.active,
      'Protocolo ráfaga',
      14,
      3200,
      'projectile_burst',
      {'projectiles': 3, 'damage_basis_points': 4500},
    ),
    _skill(
      CharacterId.jano,
      'jano_quickdraw',
      SkillSlot.passive,
      'Desenfunde',
      8,
      1800,
      'cooldown_reduction',
      {'basis_points': 1000},
    ),
    _skill(
      CharacterId.jano,
      'jano_scavenger_sight',
      SkillSlot.passive,
      'Mira oportunista',
      20,
      4200,
      'precision_score_bonus',
      {'basis_points': 500, 'encounter_cap': 500},
    ),
    _skill(
      CharacterId.parker,
      'parker_guard_dash',
      SkillSlot.active,
      'Embestida guardiana',
      5,
      1200,
      'guard_dash',
      {'duration_ms': 450, 'cooldown_ms': 12000},
    ),
    _skill(
      CharacterId.parker,
      'parker_rally',
      SkillSlot.active,
      'Último aliento',
      14,
      3200,
      'last_life_rally',
      {'duration_ms': 2500, 'uses_per_stage': 1},
    ),
    _skill(
      CharacterId.parker,
      'parker_reinforced_vest',
      SkillSlot.passive,
      'Chaleco reforzado',
      8,
      1800,
      'post_hit_invulnerability',
      {'basis_points': 1000},
    ),
    _skill(
      CharacterId.parker,
      'parker_second_wind',
      SkillSlot.passive,
      'Segundo aire',
      20,
      4200,
      'recovery_after_life_loss',
      {'basis_points': 1000, 'duration_ms': 4000},
    ),
    _skill(
      CharacterId.chema,
      'chema_shield_pulse',
      SkillSlot.active,
      'Pulso de escudo',
      5,
      1200,
      'shield_pulse',
      {'radius': 180, 'damage_basis_points': 6000},
    ),
    _skill(
      CharacterId.chema,
      'chema_debt_discharge',
      SkillSlot.active,
      'Descarga de deuda',
      14,
      3200,
      'penalty_discharge',
      {'conversion_basis_points': 5000, 'stage_cap': 750},
    ),
    _skill(
      CharacterId.chema,
      'chema_capacitor',
      SkillSlot.passive,
      'Capacitor estable',
      8,
      1800,
      'shield_regeneration',
      {'basis_points': 1000},
    ),
    _skill(
      CharacterId.chema,
      'chema_score_insurance',
      SkillSlot.passive,
      'Seguro de puntos',
      20,
      4200,
      'shield_penalty_reduction',
      {'basis_points': 2000},
    ),
    _skill(
      CharacterId.conra,
      'conra_phase_dash',
      SkillSlot.active,
      'Paso espectral',
      5,
      1200,
      'phase_dash',
      {'distance': 160, 'duration_ms': 350},
    ),
    _skill(
      CharacterId.conra,
      'conra_spectral_decoy',
      SkillSlot.active,
      'Señuelo espectral',
      14,
      3200,
      'spectral_decoy',
      {'duration_ms': 1800, 'uses_per_stage': 2},
    ),
    _skill(
      CharacterId.conra,
      'conra_lingering_veil',
      SkillSlot.passive,
      'Velo persistente',
      8,
      1800,
      'intangibility_duration',
      {'basis_points': 1000},
    ),
    _skill(
      CharacterId.conra,
      'conra_phase_reserve',
      SkillSlot.passive,
      'Reserva de fase',
      20,
      4200,
      'phase_exit_grace',
      {'duration_ms': 300},
    ),
    _skill(
      CharacterId.shyno,
      'shyno_aerial_stomp',
      SkillSlot.active,
      'Pisotón aéreo',
      5,
      1200,
      'aerial_stomp',
      {'radius': 150, 'damage_basis_points': 7000},
    ),
    _skill(
      CharacterId.shyno,
      'shyno_wind_burst',
      SkillSlot.active,
      'Ráfaga ascendente',
      14,
      3200,
      'vertical_burst',
      {'impulse_basis_points': 4500},
    ),
    _skill(
      CharacterId.shyno,
      'shyno_spring_heels',
      SkillSlot.passive,
      'Talones de resorte',
      8,
      1800,
      'double_jump_control',
      {'basis_points': 1000},
    ),
    _skill(
      CharacterId.shyno,
      'shyno_landing_rhythm',
      SkillSlot.passive,
      'Ritmo de aterrizaje',
      20,
      4200,
      'precision_landing_cooldown',
      {'reduction_ms': 800, 'minimum_cooldown_ms': 4000},
    ),
    _skill(
      CharacterId.nakama,
      'nakama_tailwind',
      SkillSlot.active,
      'Viento de cola',
      5,
      1200,
      'glide_tailwind',
      {'duration_ms': 900, 'speed_basis_points': 1200},
    ),
    _skill(
      CharacterId.nakama,
      'nakama_feather_guard',
      SkillSlot.active,
      'Guardia de plumas',
      14,
      3200,
      'glide_projectile_guard',
      {'uses_per_stage': 1, 'duration_ms': 1600},
    ),
    _skill(
      CharacterId.nakama,
      'nakama_thermal_lift',
      SkillSlot.passive,
      'Corriente térmica',
      8,
      1800,
      'glide_fall_reduction',
      {'basis_points': 1000, 'duration_ms': 1200},
    ),
    _skill(
      CharacterId.nakama,
      'nakama_soft_landing',
      SkillSlot.passive,
      'Aterrizaje suave',
      20,
      4200,
      'glide_landing_recovery',
      {'basis_points': 1000, 'duration_ms': 2000},
    ),
    _skill(
      CharacterId.nanic,
      'nanic_arc_burst',
      SkillSlot.active,
      'Arco voltaico',
      5,
      1200,
      'electric_chain',
      {'targets': 2, 'damage_basis_points': 6500},
    ),
    _skill(
      CharacterId.nanic,
      'nanic_overclock',
      SkillSlot.active,
      'Sobrecarga',
      14,
      3200,
      'energy_overclock',
      {
        'duration_ms': 3000,
        'speed_basis_points': 1000,
        'damage_basis_points': 1000,
      },
    ),
    _skill(
      CharacterId.nanic,
      'nanic_efficient_charge',
      SkillSlot.passive,
      'Carga eficiente',
      8,
      1800,
      'first_orb_double_charge',
      {'uses_per_stage': 1},
    ),
    _skill(
      CharacterId.nanic,
      'nanic_residual_field',
      SkillSlot.passive,
      'Campo residual',
      20,
      4200,
      'discharge_grace',
      {'duration_ms': 350},
    ),
  ]);

  static ProgressionSnapshot preview(
    CharacterId characterId,
    String contentVersion,
  ) {
    final definition = characterId.definition;
    return ProgressionSnapshot(
      characterId: characterId,
      contentVersion: contentVersion,
      contentDigest: List.filled(64, '0').join(),
      masteryXp: 0,
      masteryLevel: 0,
      nextLevelXp: 100,
      bankedCurrency: 0,
      temporaryCurrency: 0,
      storeUnlocked: false,
      authorizedBuild: AuthorizedBuild(
        speedBasisPoints: 0,
        jumpBasisPoints: 0,
        damageBasisPoints: 0,
        vitalityBasisPoints: 0,
        fortuneBasisPoints: 0,
        maxLives: definition.baseLives,
        activeSkillId: null,
        defaultActiveId: definition.defaultActive?.name,
        passiveSkillIds: const [],
        skinId: '${characterId.serialized}_default',
      ),
      stats: const [
        ProgressionStat(
          id: 'speed',
          displayName: 'Velocidad',
          description:
              'Cadencia, movimiento de boss y recuperación; no acelera el mundo.',
          rank: 0,
          maxRank: 5,
          effectiveBasisPoints: 0,
          nextCost: 200,
          nextUnlockLevel: 1,
          nextBonusBasisPoints: 200,
        ),
        ProgressionStat(
          id: 'jump',
          displayName: 'Salto',
          description: 'Impulso de salto, con tope total de +10%.',
          rank: 0,
          maxRank: 5,
          effectiveBasisPoints: 0,
          nextCost: 200,
          nextUnlockLevel: 1,
          nextBonusBasisPoints: 200,
        ),
        ProgressionStat(
          id: 'damage',
          displayName: 'Daño',
          description: 'Daño contra enemigos y bosses, con tope de +50%.',
          rank: 0,
          maxRank: 5,
          effectiveBasisPoints: 0,
          nextCost: 250,
          nextUnlockLevel: 1,
          nextBonusBasisPoints: 1000,
        ),
        ProgressionStat(
          id: 'vitality',
          displayName: 'Vitalidad',
          description:
              'Invulnerabilidad posterior al daño y una vida al rango cinco.',
          rank: 0,
          maxRank: 5,
          effectiveBasisPoints: 0,
          nextCost: 300,
          nextUnlockLevel: 2,
          nextBonusBasisPoints: 200,
        ),
        ProgressionStat(
          id: 'fortune',
          displayName: 'Fortuna',
          description: 'Moneda obtenida en Progresión, con tope de +15%.',
          rank: 0,
          maxRank: 5,
          effectiveBasisPoints: 0,
          nextCost: 250,
          nextUnlockLevel: 2,
          nextBonusBasisPoints: 300,
        ),
      ],
      skills: skills
          .where((skill) => skill.characterId == characterId)
          .toList(),
      palettes: [
        PaletteVariant(
          id: '${characterId.serialized}_default',
          characterId: characterId,
          displayName: 'Original',
          hueShift: 0,
          saturationBasisPoints: 10000,
          valueBasisPoints: 10000,
          unlockLevel: 0,
          cost: 0,
          owned: true,
          equipped: true,
        ),
        PaletteVariant(
          id: '${characterId.serialized}_aurora',
          characterId: characterId,
          displayName: 'Aurora',
          hueShift: 55,
          saturationBasisPoints: 11200,
          valueBasisPoints: 10800,
          unlockLevel: 3,
          cost: 800,
          owned: false,
          equipped: false,
        ),
        PaletteVariant(
          id: '${characterId.serialized}_eclipse',
          characterId: characterId,
          displayName: 'Eclipse',
          hueShift: 210,
          saturationBasisPoints: 9000,
          valueBasisPoints: 7800,
          unlockLevel: 10,
          cost: 1800,
          owned: false,
          equipped: false,
        ),
      ],
    );
  }

  static ProgressionSkill _skill(
    CharacterId characterId,
    String id,
    SkillSlot slot,
    String name,
    int unlockLevel,
    int cost,
    String effectCode,
    Map<String, Object?> parameters,
  ) {
    return ProgressionSkill(
      id: id,
      characterId: characterId,
      slot: slot,
      displayName: name,
      description: _effectDescription(effectCode),
      unlockLevel: unlockLevel,
      cost: cost,
      effectCode: effectCode,
      effectParameters: parameters,
      uiExplanation: _effectDescription(effectCode),
      compatibleModes: const [RunMode.progression, RunMode.bossRush],
      owned: false,
    );
  }

  static String _effectDescription(String effectCode) => switch (effectCode) {
    'ricochet_projectile' => 'Un rebote controlado al 80% de daño.',
    'projectile_burst' => 'Tres disparos limitados con un solo cooldown.',
    'cooldown_reduction' => '10% menos recuperación para proyectiles.',
    'precision_score_bonus' =>
      'Bonificación de precisión con tope por encuentro.',
    'guard_dash' => 'Carrera defensiva breve que no repone vidas.',
    'last_life_rally' => 'Recuperación breve, una vez por nivel.',
    'post_hit_invulnerability' => '10% más ventana posterior al daño.',
    'recovery_after_life_loss' => 'Recuperación temporal tras perder una vida.',
    'shield_pulse' => 'Pulso de área que no reinicia el escudo innato.',
    'penalty_discharge' => 'Convierte penalización reciente en daño limitado.',
    'shield_regeneration' => '10% menos espera del escudo innato.',
    'shield_penalty_reduction' => 'Reduce 20% la penalización del escudo.',
    'phase_dash' => 'Avance corto en fase, limitado por el encuentro.',
    'spectral_decoy' => 'Atrae ataques dirigidos, no ataques de área.',
    'intangibility_duration' => '10% más duración de intangibilidad.',
    'phase_exit_grace' => '300 ms de gracia al salir de fase.',
    'aerial_stomp' => 'Daño de área al aterrizar desde el aire.',
    'vertical_burst' => 'Impulso breve que no concede un tercer salto.',
    'double_jump_control' => '10% más control durante el segundo salto.',
    'precision_landing_cooldown' => 'Aterrizajes precisos reducen hasta 0.8 s.',
    'glide_tailwind' => 'Impulso horizontal sólo durante el planeo.',
    'glide_projectile_guard' => 'Amortigua un proyectil por nivel.',
    'glide_fall_reduction' => '10% menos caída al iniciar el planeo.',
    'glide_landing_recovery' => 'Recuperación breve tras aterrizar planeando.',
    'electric_chain' => 'Encadena daño a dos objetivos y consume carga.',
    'energy_overclock' => 'Potencia daño y cadencia durante tres segundos.',
    'first_orb_double_charge' => 'El primer orbe del nivel cuenta doble.',
    'discharge_grace' => '350 ms de gracia después de descargar.',
    _ => 'Efecto exclusivo y limitado de este personaje.',
  };
}
